# .github/workflows/deploy-backend.yml (TEMPORARY DEBUG)
name: Deploy Backend to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Test basic command
        run: echo "Workflow is running basic steps."

      # - name: Deploy to Railway # TEMPORARILY COMMENTED OUT
      #   uses: railwayapp/cli-action@v1
      #   with:
      #     railway_token: ${{ secrets.RAILWAY_TOKEN }}
      #   env:
      #     RAILWAY_ENVIRONMENT: production