# .github/workflows/deploy-backend.yml
name: Deploy Backend to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code # Added name for clarity
        uses: actions/checkout@v3

      - name: Deploy to Railway # Make sure this step is present and uncommented
        uses: railwayapp/cli-action@v1
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
        env:
          RAILWAY_ENVIRONMENT: production # Optional, adjust as needed