name: Deploy to Railway
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: 091fd195-a786-4b30-b573-a7de0f33e509
      RAILWAY_TOKEN: 996153b1-da94-4ff6-a99c-7c549530b885
    steps:
      - uses: actions/checkout@v3
      - run: railway up --service=${{ env.SVC_ID }}
